### ISSUE TITLE
Mirrorlist choosing window

### ISSUE THREAD

**Issue by antoniovazquezblanco** [antoniovazquezblanco/ArchSetup#17]
Depends on #15 for list selection.

**Comment by mame98** [comment]
What about an automatic selection with `Reflector`?
- [Reflector - ArchWiki](https://wiki.archlinux.org/index.php/Reflector)

So for example just call:
`reflector --verbose -l 25 -p http --sort rate --save /mnt/etc/pacman.d/mirrorlist`
to get the 25 most up-to-date servers, which are sorted by download speed

**Comment by antoniovazquezblanco** [comment]
I didn't knew about it but is seems a very valid option for me.

**Comment by mame98** [comment]
yes, I think selecting mirrorlists manualy could be quite confusing... ;-)
Anyways, I want to start working on this, but (i think) the tool is not installed on the installation ISO... (is `python` installed?)
I think there are two options:
- Check software at startup
- Use script to get software (prefered)

So you can run the script **before** the main setup...
Might use a second script for the 'real' installation, so `python ArchSetup` will not trigger the software script... (better for developing!)

So instead of running `python ArchSetup` on the instal ISO, you could use `./install.sh` (or something like that ;-)) which runs in two stages:
1. Install software (if missing)
2. Run `python ArchSetup`

What do you think?

**Comment by antoniovazquezblanco** [comment]
Sorry I can't spend a lot of time on this tool lately but I'm preparing my engineering degree final project.
I think we should check if python is installed in the ISO. If it is I would prefer to add a section of prerequisites to ArchSetup.

What do you think?
Thanks for your work on this!

**Comment by mame98** [comment]
no problem ;-) I like the idea...
But I think there must be an cmdline option to skip prerequisites test...

**Comment by antoniovazquezblanco** [comment]
I think we reached an agreement ;). Sounds nice.

Thanks

**Comment by mame98** [comment]
cool ! I will start working on this tomorrow...

**Comment by antoniovazquezblanco** [comment]
Implemented in #25. Solved!
